### ISSUE TITLE
what are the teams for?

### ISSUE THREAD

**Issue by VadneyK** [zeitgeistpm/discord-faucet#1]
Hello, I'm trying to make a discord faucet for plasm on substrate as well and was looking at you code.

I saw that you have a team constant to give different amounts of your coin to these members in the channel.

What's the purpose of having the two team and Team groups? 
<img width="479" alt="Screen Shot 2021-05-30 at 3 57 04 PM" src="https://user-images.githubusercontent.com/57117207/120122761-af2dcb80-c15f-11eb-85b6-f9ebe2c2fbf2.png">

**Comment by saboonikhil** [comment]
Ah, apologies for the delay in replying. 
I guess you must have figured it out by now, but let me try to answer: We have assigned roles to users which are part of the team (`smallTeam`) or admin (`bigTeam`) as a distinction. We allow these two roles to choose the number of `ZBS` tokens they wish to receive. If they don't choose, they get `1 ZBS` by default. Thanks!
